dist: trusty

language: node_js

node_js:
  - "8"
  - "6"

addons:
  chrome: stable

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

after_success:
  - node ./scripts/prepare-package
  - cd dist
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
