dist: trusty

language: node_js

addons:
  chrome: stable

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
        - node ./scripts/prepare-package
        - cd dist
        - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
